# Generated by Django 4.1.3 on 2023-04-13 08:17

import Comics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('name', models.CharField(max_length=10000)),
                ('slug', models.CharField(max_length=10000, unique=True)),
                ('numPages', models.IntegerField(default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('numReviews', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-updated', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('title', models.CharField(max_length=1000, unique=True)),
                ('alternativetitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_urls', models.URLField(max_length=10000)),
                ('images', models.ImageField(max_length=100000, upload_to=Comics.models.comics_images_location, verbose_name='Images')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('Completed', 'completed'), ('Ongoing', 'ongoing'), ('Dropped', 'dropped'), ('Coming_Soon', 'coming_soon'), ('Hiatus', 'hiatus')], max_length=11)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('released', models.CharField(blank=True, max_length=100, null=True)),
                ('serialization', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=1000, null=True)),
                ('numChapters', models.IntegerField(default=0)),
                ('numReviews', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comics.category')),
                ('favourites', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('url', models.URLField(max_length=10000, null=True, unique=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('images', models.ImageField(max_length=100000, upload_to=Comics.models.comics_chapters_images_location, verbose_name='Images')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comics.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptercomments', to='Comics.chapter')),
                ('comic', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comiccomments', to='Comics.comic')),
                ('owner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddField(
            model_name='comic',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genre', to='Comics.genre'),
        ),
        migrations.AddField(
            model_name='comic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comic',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comics.website'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comics.comic'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='page', to='Comics.page'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comics.website'),
        ),
    ]
