export const COMICS_BOOKMARK_ADD_REQUEST = "COMICS_BOOKMARK_ADD_REQUEST";
export const COMICS_BOOKMARK_ADD_SUCCESS = "COMICS_BOOKMARK_ADD_SUCCESS";
export const COMICS_BOOKMARK_ADD_FAIL = "COMICS_BOOKMARK_ADD_FAIL";

export const COMICS_BOOKMARK_LIST_REQUEST = "COMICS_BOOKMARK_LIST_REQUEST";
export const COMICS_BOOKMARK_LIST_SUCCESS = "COMICS_BOOKMARK_LIST_SUCCESS";
export const COMICS_BOOKMARK_LIST_FAIL = "COMICS_BOOKMARK_LIST_FAIL";

export const COMICS_BOOKMARK_LIKE_REQUEST = "COMICS_BOOKMARK_LIKE_REQUEST";
export const COMICS_BOOKMARK_LIKE_SUCCESS = "COMICS_BOOKMARK_LIKE_SUCCESS";
export const COMICS_BOOKMARK_LIKE_FAIL = "COMICS_BOOKMARK_LIST_FAIL";
