export const CHAPTERS_LIST_REQUEST = "CHAPTERS_LIST_REQUEST";
export const CHAPTERS_LIST_SUCCESS = "CHAPTERS_LIST_SUCCESS";
export const CHAPTERS_LIST_FAIL = "CHAPTERS_LIST_FAIL";

export const CHAPTERS_DETAILS_REQUEST = "CHAPTERS_DETAILS_REQUEST";
export const CHAPTERS_DETAILS_SUCCESS = "CHAPTERS_DETAILS_SUCCESS";
export const CHAPTERS_DETAILS_FAIL = "CHAPTERS_DETAILS_FAIL";

export const CHAPTERS_DELETE_REQUEST = "CHAPTERS_DELETE_REQUEST";
export const CHAPTERS_DELETE_SUCCESS = "CHAPTERS_DELETE_SUCCESS";
export const CHAPTERS_DELETE_FAIL = "CHAPTERS_DELETE_FAIL";

export const CHAPTERS_CREATE_REQUEST = "CHAPTERS_CREATE_REQUEST";
export const CHAPTERS_CREATE_SUCCESS = "CHAPTERS_CREATE_SUCCESS";
export const CHAPTERS_CREATE_FAIL = "CHAPTERS_CREATE_FAIL";
export const CHAPTERS_CREATE_RESET = "CHAPTERS_CREATE_RESET";

export const CHAPTERS_UPDATE_REQUEST = "CHAPTERS_UPDATE_REQUEST";
export const CHAPTERS_UPDATE_SUCCESS = "CHAPTERS_UPDATE_SUCCESS";
export const CHAPTERS_UPDATE_FAIL = "CHAPTERS_UPDATE_FAIL";
export const CHAPTERS_UPDATE_RESET = "CHAPTERS_UPDATE_RESET";

export const CHAPTERS_TOP_REQUEST = "CHAPTERS_TOP_REQUEST";
export const CHAPTERS_TOP_SUCCESS = "CHAPTERS_TOP_SUCCESS";
export const CHAPTERS_TOP_FAIL = "CHAPTERS_TOP_FAIL";

export const CHAPTER_CREATE_REVIEW_REQUEST = "CHAPTER_CREATE_REVIEW_REQUEST";
export const CHAPTER_CREATE_REVIEW_SUCCESS = "CHAPTER_CREATE_REVIEW_SUCCESS";
export const CHAPTER_CREATE_REVIEW_FAIL = "CHAPTER_CREATE_REVIEW_FAIL";
export const CHAPTER_CREATE_REVIEW_RESET = "CHAPTER_CREATE_REVIEW_RESET";