export const COMICS_LIST_REQUEST = "COMICS_LIST_REQUEST";
export const COMICS_LIST_SUCCESS = "COMICS_LIST_SUCCESS";
export const COMICS_LIST_FAIL = "COMICS_LIST_FAIL";
export const COMICS_LIST_RESET = "COMICS_LIST_RESET";

export const COMICS_DETAILS_REQUEST = "COMICS_DETAILS_REQUEST";
export const COMICS_DETAILS_SUCCESS = "COMICS_DETAILS_SUCCESS";
export const COMICS_DETAILS_FAIL = "COMICS_DETAILS_FAIL";
export const COMICS_DETAILS_RESET = "COMICS_DETAILS_RESET";

export const COMICS_DELETE_REQUEST = "COMICS_DELETE_REQUEST";
export const COMICS_DELETE_SUCCESS = "COMICS_DELETE_SUCCESS";
export const COMICS_DELETE_FAIL = "COMICS_DELETE_FAIL";

export const COMICS_CREATE_REQUEST = "COMICS_CREATE_REQUEST";
export const COMICS_CREATE_SUCCESS = "COMICS_CREATE_SUCCESS";
export const COMICS_CREATE_FAIL = "COMICS_CREATE_FAIL";
export const COMICS_CREATE_RESET = "COMICS_CREATE_RESET";

export const COMICS_UPDATE_REQUEST = "COMICS_UPDATE_REQUEST";
export const COMICS_UPDATE_SUCCESS = "COMICS_UPDATE_SUCCESS";
export const COMICS_UPDATE_FAIL = "COMICS_UPDATE_FAIL";
export const COMICS_UPDATE_RESET = "COMICS_UPDATE_RESET";

export const COMICS_TOP_REQUEST = "COMICS_TOP_REQUEST";
export const COMICS_TOP_SUCCESS = "COMICS_TOP_SUCCESS";
export const COMICS_TOP_FAIL = "COMICS_TOP_FAIL";
