export const GENRES_LIST_REQUEST = "GENRES_LIST_REQUEST";
export const GENRES_LIST_SUCCESS = "GENRES_LIST_SUCCESS";
export const GENRES_LIST_FAIL = "GENRES_LIST_FAIL";

export const GENRES_DETAILS_REQUEST = "GENRES_DETAILS_REQUEST";
export const GENRES_DETAILS_SUCCESS = "GENRES_DETAILS_SUCCESS";
export const GENRES_DETAILS_FAIL = "GENRES_DETAILS_FAIL";
